seed: 42
epochs: 10
batch_size: 64
layer_dims: [1, 16, 32, 64, 128]
kernel_size: 3
learning_rate: 0.0004
weight_decay: 0.1
warmup_percentage: 0.05
decay_percentage: 0.1
dtype: float32
checkpoint_freq: 5
results_dir: results
exp_name: baseline