seed: 42
epochs: 10
batch_size: 32
layer_dims: [1, 32, 64]
fc_out_dim: 128
kernel_size: 3
learning_rate: 0.001
scale_by_adam: false
weight_decay: 0.
warmup_percentage: 0.
decay_percentage: 0.
dtype: float16
checkpoint_freq: 5
normalization_mode: global
augment: true
results_dir: results
exp_name: baselinehalfaugment